services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: engineer
      POSTGRES_PASSWORD: notroot
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Server/Flask
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://engineer:notroot@db:5432/database"
    volumes:
      - ./Server/Flask:/app

  frontend:
    build:
      context: ./Client/TypeScript
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: