/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoutesImport } from './routes/Routes'
import { Route as ProtectedRouteImport } from './routes/ProtectedRoute'

// Create/Update Routes

const RoutesRoute = RoutesImport.update({
  path: '/Routes',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRouteRoute = ProtectedRouteImport.update({
  path: '/ProtectedRoute',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ProtectedRoute': {
      id: '/ProtectedRoute'
      path: '/ProtectedRoute'
      fullPath: '/ProtectedRoute'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRoute
    }
    '/Routes': {
      id: '/Routes'
      path: '/Routes'
      fullPath: '/Routes'
      preLoaderRoute: typeof RoutesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  ProtectedRouteRoute,
  RoutesRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": [
        "/ProtectedRoute",
        "/Routes"
      ]
    },
    "/ProtectedRoute": {
      "filePath": "ProtectedRoute.tsx"
    },
    "/Routes": {
      "filePath": "Routes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
